-- PostgreSQL schema for Lalana models
-- Generated from Java entity classes

-- Drop tables if they exist (reverse dependency order)
DROP TABLE IF EXISTS probleme_history CASCADE;
DROP TABLE IF EXISTS signalement_history CASCADE;
DROP TABLE IF EXISTS signalement_images CASCADE;
DROP TABLE IF EXISTS probleme CASCADE;
DROP TABLE IF EXISTS probleme_status CASCADE;
DROP TABLE IF EXISTS signalement CASCADE;
DROP TABLE IF EXISTS signalement_status CASCADE;
DROP TABLE IF EXISTS users_history CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS entreprise CASCADE;
DROP TABLE IF EXISTS config CASCADE;

-- Create config
CREATE TABLE IF NOT EXISTS config (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	key varchar NOT NULL,
	valeur text NOT NULL
);

-- Entreprise
CREATE TABLE IF NOT EXISTS entreprise (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nom varchar(100) NOT NULL,
	adresse varchar(255),
	telephone varchar(20)
);

-- Points (geolocation)
CREATE TABLE IF NOT EXISTS points (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	x double precision NOT NULL,
	y double precision NOT NULL,
	localisation varchar(255) NOT NULL,
	firestore_synced boolean NOT NULL DEFAULT FALSE
);

-- Users
CREATE TABLE IF NOT EXISTS users (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar(50),
	password varchar(255) NOT NULL,
	firebase_token varchar(255),
	current_status integer NOT NULL DEFAULT 1,
	firestore_synced boolean NOT NULL DEFAULT FALSE,
	fcm_token varchar(250)
);

-- Signalement status
CREATE TABLE IF NOT EXISTS signalement_status (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nom varchar(50) NOT NULL,
	description text,
	firestore_synced boolean NOT NULL DEFAULT FALSE,
	valeur integer NOT NULL
);

-- Signalement
CREATE TABLE IF NOT EXISTS signalement (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id integer REFERENCES users(id) ON DELETE SET NULL,
	point_id integer REFERENCES points(id) ON DELETE SET NULL,
	description text,
	created_at timestamp,
	status_id integer REFERENCES signalement_status(id) ON DELETE SET NULL,
	firestore_synced boolean NOT NULL DEFAULT FALSE
);

-- Signalement images
CREATE TABLE IF NOT EXISTS signalement_images (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	signalement_id integer REFERENCES signalement(id) ON DELETE CASCADE,
	chemin_local varchar(1024),
	chemin_online varchar(1024),
	nom_fichier varchar(255)
);

-- Probleme status
CREATE TABLE IF NOT EXISTS probleme_status (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nom varchar(50) NOT NULL,
	description text,
	firestore_synced boolean NOT NULL DEFAULT FALSE,
	valeur integer NOT NULL
);

-- Probleme
CREATE TABLE IF NOT EXISTS probleme (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	signalement_id integer REFERENCES signalement(id) ON DELETE SET NULL,
	surface double precision NOT NULL,
	budget_estime double precision NOT NULL,
	entreprise_id integer REFERENCES entreprise(id) ON DELETE SET NULL,
	status_id integer REFERENCES probleme_status(id) ON DELETE SET NULL,
	niveau integer NOT NULL,
	firestore_synced boolean NOT NULL DEFAULT FALSE
);

-- Signalement history
CREATE TABLE IF NOT EXISTS signalement_history (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	signalement_id integer REFERENCES signalement(id) ON DELETE CASCADE,
	status_id integer REFERENCES signalement_status(id) ON DELETE SET NULL,
	changed_at timestamp
);

-- Probleme history
CREATE TABLE IF NOT EXISTS probleme_history (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	probleme_id integer REFERENCES probleme(id) ON DELETE CASCADE,
	status_id integer REFERENCES probleme_status(id) ON DELETE SET NULL,
	changed_at timestamp
);

-- Users history
CREATE TABLE IF NOT EXISTS users_history (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id integer REFERENCES users(id) ON DELETE CASCADE,
	changed_at timestamp,
	status integer NOT NULL
);

-- Indexes to speed up joins and lookups
CREATE INDEX IF NOT EXISTS idx_signalement_user ON signalement(user_id);
CREATE INDEX IF NOT EXISTS idx_signalement_point ON signalement(point_id);
CREATE INDEX IF NOT EXISTS idx_signalement_status ON signalement(status_id);
CREATE INDEX IF NOT EXISTS idx_probleme_signalement ON probleme(signalement_id);
CREATE INDEX IF NOT EXISTS idx_probleme_entreprise ON probleme(entreprise_id);
CREATE INDEX IF NOT EXISTS idx_probleme_status ON probleme(status_id);
CREATE INDEX IF NOT EXISTS idx_signalement_images_signalement ON signalement_images(signalement_id);

-- Example seed for config (PM2)
INSERT INTO config (key, valeur)
SELECT 'PM2', '5000' WHERE NOT EXISTS (SELECT 1 FROM config WHERE key = 'PM2');


-- signalement statuses
INSERT INTO signalement_status (id, nom, description,valeur) VALUES
(1, 'Nouveau', 'Signalement nouvellement cree', 10),
(2, 'En cours', 'Signalement en cours de traitement', 20),
(3, 'Resolu', 'Signalement traite et resolu', 30);

-- probleme statuses
INSERT INTO probleme_status (id, nom, description, valeur) VALUES
(1, 'Ouvert', 'Probleme ouvert', 10),
(2, 'Assigne', 'Probleme assigne q une entreprise', 20),
(3, 'Termine', 'Travail termine', 30);

INSERT INTO entreprise (id, nom, adresse, telephone) VALUES
(1, 'Entreprise Travaux SA', '123 Rue Principale, Antananarivo', '+261202000001'),
(2, 'Entreprise B', 'Analakely, Antananarivo', '+261203048765');


INSERT INTO users ( email, password, fcm_token, firebase_token, firestore_synced) VALUES
('admin@lalana.mg', 'admin123', NULL, 'ts2LXs3eOzgP1z1DB1ffNk4xxWh2', TRUE);
-- End of script

